[package]
name = "hft-metrics"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
metrics.workspace = true
metrics-exporter-prometheus.workspace = true
parking_lot.workspace = true
serde.workspace = true
chrono.workspace = true
